// crates/setu-move-vm/build.rs
//
// Embeds setu-framework/compiled/*.mv as Rust constants via include_bytes!().
// Does NOT require any external crates — pure std only.
//
// If .mv files are missing (Sui CLI not installed), generates an empty array
// so compilation still succeeds. Tests skip gracefully when STDLIB_MODULES is empty.

use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());

    // setu-framework/compiled/ relative to workspace root
    // crates/setu-move-vm/ → parent = crates/ → parent = workspace root
    let compiled_dir = match std::env::var("SETU_FRAMEWORK_DIR") {
        Ok(dir) => PathBuf::from(dir).join("compiled"),
        Err(_) => manifest_dir
            .parent()
            .unwrap() // crates/
            .parent()
            .unwrap() // workspace root
            .join("setu-framework")
            .join("compiled"),
    };

    let modules = &[
        "object",
        "transfer",
        "tx_context",
        "balance",
        "coin",
        "setu",
        "vector",
        "option",
        "string",
        "vec_map",
        "vec_set",
        "event",
    ];

    let mut code = String::from(
        "/// Setu stdlib pre-compiled bytecodes (generated by build.rs)\n\
         pub const STDLIB_MODULES: &[(&str, &[u8])] = &[\n",
    );

    let mut all_found = true;
    for name in modules {
        let mv_path = compiled_dir.join(format!("{}.mv", name));
        if mv_path.exists() {
            // Use canonical path for include_bytes!
            let canonical = mv_path
                .canonicalize()
                .unwrap_or_else(|_| mv_path.clone());
            code.push_str(&format!(
                "    (\"{name}\", include_bytes!(\"{}\")),\n",
                canonical.display()
            ));
        } else {
            eprintln!(
                "cargo:warning=Missing stdlib module: {}. \
                 Run: bash scripts/build_stdlib.sh",
                mv_path.display()
            );
            all_found = false;
        }
    }

    code.push_str("];\n");

    // If not all modules found, generate empty array so compilation still works
    if !all_found {
        code = String::from(
            "/// Setu stdlib (EMPTY — .mv files not found, run: bash scripts/build_stdlib.sh)\n\
             pub const STDLIB_MODULES: &[(&str, &[u8])] = &[];\n",
        );
    }

    let output_path = PathBuf::from(&out_dir).join("stdlib_modules.rs");
    fs::write(&output_path, &code).expect("Failed to write stdlib_modules.rs");

    // Rerun when compiled/ directory changes
    println!("cargo:rerun-if-changed={}", compiled_dir.display());
    for name in modules {
        println!(
            "cargo:rerun-if-changed={}/{}.mv",
            compiled_dir.display(),
            name
        );
    }
}
